# Generated by Django 5.2.2 on 2025-07-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sobre_mi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
